apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-api-rest
  name: flask-api-rest
  namespace: default
spec:
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-api-rest
  type: NodePort
