apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: khalibad/ms-ui-rdv:0.0.2
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: "mongodb+srv://badiaka:Physicien02@cluster0.yekdqj3.mongodb.net/?appName=Cluster0"
